# Generated by Django 4.1.13 on 2024-08-14 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_course_result_trainingsession_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instruction', models.TextField()),
                ('order_in_session', models.IntegerField()),
                ('task_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='course',
        ),
        migrations.AlterField(
            model_name='course',
            name='training_sessions',
            field=models.ManyToManyField(blank=True, related_name='courses', to='users.trainingsession'),
        ),
        migrations.AlterField(
            model_name='result',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='results',
        ),
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_users', to='users.course'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('order_in_activity', models.IntegerField()),
                ('value', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.activity')),
            ],
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='users.activity'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='users.result'),
        ),
    ]
