# Generated by Django 5.1 on 2024-08-16 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_activity_remove_trainingsession_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(related_name='teaching_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
