# Generated by Django 5.1 on 2024-08-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_course_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('texto_completo', 'Texto Completo'), ('palabras_sueltas', 'Palabras Sueltas')], default='texto_completo', max_length=20),
        ),
    ]
