# Generated by Django 5.1 on 2024-08-17 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_result_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='session',
        ),
        migrations.CreateModel(
            name='UserActivityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.activity')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trainingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'activity', 'session')},
            },
        ),
    ]
