# Generated by Django 5.1 on 2024-08-17 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_activity_completed_remove_activity_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activity_list', to='users.trainingsession'),
        ),
        migrations.DeleteModel(
            name='UserActivityStatus',
        ),
    ]
