# Generated by Django 5.1 on 2024-08-18 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_result_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.course'),
        ),
    ]
