# Generated by Django 5.1 on 2024-08-18 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_trainingsession_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.course'),
        ),
    ]
