# Generated by Django 5.1 on 2024-08-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_result_course_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='date',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='name',
            field=models.CharField(default='Sesion', max_length=255),
        ),
    ]
