# Generated by Django 5.1 on 2024-08-19 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_activity_id_alter_activity_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_list', to='users.trainingsession'),
        ),
    ]
