# Generated by Django 5.1 on 2024-08-19 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_activity_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='actividades', to='users.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_items', to='users.activity'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
