# Generated by Django 5.1 on 2024-08-19 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_activity_items_alter_item_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='items',
        ),
        migrations.AlterField(
            model_name='item',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.activity'),
        ),
    ]
